# Default (systemd) user-specific environment setup
# https://wiki.archlinux.org/title/environment_variables#Per_user
#
# Note: Changes here will only apply consistently _after_ new session login.

# Ensure that assumed XDG variables exist
#  - https://wiki.archlinux.org/title/XDG_Base_Directory
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

# XDG specification does not define this variable but it is mentioned/assumed
# by some apps/libs (e.g. `ghcup`) so it might be useful to export it anyway.
#  - https://www.haskell.org/ghcup/guide/#xdg-support
XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}

# This variable is not set by default but is defined in the XDG specification.
XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}

# Custom extended XDG Base Directory specification
XDG_DEV_HOME=$HOME/.local/dev
XDG_TMP_HOME=$HOME/.cache/tmp

# Editor setup
VISUAL=nvim
EDITOR=${VISUAL}
VIMRC=${XDG_CONFIG_HOME}/vim/vimrc

# Browser setup
BROWSER=firefox

# Personal user info
NAME="Martin Matyášek"
EMAIL=martin.matyasek@gmail.com

# Bat
BAT_CONFIG_DIR=${XDG_CONFIG_HOME}/bat
BAT_CONFIG_PATH=${BAT_CONFIG_DIR}/config

# Go lang
GOPATH=${XDG_DATA_HOME}/go
GOBIN=${GOPATH}/bin

# rg
RIPGREP_CONFIG_HOME=${XDG_CONFIG_HOME}/rg
RIPGREP_CONFIG_PATH=${RIPGREP_CONFIG_HOME}/ripgreprc

# Rust
#  - See: https://doc.rust-lang.org/cargo/reference/environment-variables.html
#  - Note: Out-of-the-box XDG support is still an open issue for both `rustup`
#    and `cargo`, monitor.
#  - https://github.com/rust-lang/rustup/issues/247
#  - https://github.com/rust-lang/cargo/issues/1734
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
CARGO_HOME=${XDG_DATA_HOME}/cargo
CARGO_BIN=${CARGO_HOME}/bin
CARGO_TARGET_DIR=${XDG_CACHE_HOME}/cargo-target
CARGO_RELEASE_DIR=${CARGO_TARGET_DIR}/release
CARGO_ARTIFACTS_DIR=${CARGO_RELEASE_DIR}/artifacts

# Haskell stack
#  - Any value of `GHCUP_USE_XDG_DIRS` will enable XDG support, see:
#    https://www.haskell.org/ghcup/guide/#xdg-support
#  - Note: `XDG_BIN_HOME` will be used for storing binaries and as mentioned in
#    the docs, there might be clash with other tools using it (stack/cabal/ghc)
GHCUP_USE_XDG_DIRS=1
STACK_XDG=1
