# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
---
gui:
  nerdFontsVersion: "3"

  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

git:
  paging:
    colorArg: always
    pager: >
      delta
      --paging=never
      --syntax-theme=ansi
      --line-numbers
      --hyperlinks
      --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
