# Global settings
#shell = "bash -c '{}'"
#shell = "fish -c {}"
defualt-scheme = "base16-gruvbox-dark-hard"

# https://github.com/tinted-theming/tinted-fzf/issues/27
#hooks = ["~/.local/share/tinted-theming/tinty/repos/tinted-fzf/ansi/ansi.sh"]

# Item configuration
[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
#hook = ". %f"
hook = "source $TINTY_THEME_FILE_PATH"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-tmux"
path = "https://github.com/tinted-theming/tinted-tmux"
themes-dir = "colors"
# Check if tmux is in use and if it is, reload the config file
#hook = "tmux run 2> /dev/null && tmux source-file %f"
hook = "tmux run 2> /dev/null && tmux source-file $TINTY_THEME_FILE_PATH"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
#themes-dir = "fish"
themes-dir = "sh"
#hook = ". %f"
hook = "source $TINTY_THEME_FILE_PATH"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/alacritty"
#hook = "ln -sf %f ~/.config/alacritty/colors.toml"
#hook = "mkdir -p ~/.config/alacritty && ln -sf %f ~/.config/alacritty/colors.toml"
hook = "mkdir -p ~/.config/alacritty && ln -sf $TINTY_THEME_FILE_PATH ~/.config/alacritty/colors.toml"
supported-systems = ["base16", "base24"]

#[[items]]
#name = "tinted-nvim"
#path = "~/.local/share/nvim/lazy/tinted-nvim"
#themes-dir = "colors"
#supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-delta"
path = "https://github.com/tinted-theming/tinted-delta"
themes-dir = "configs"
supported-systems = ["base16", "base24"]

[[items]]
name = "base16-btop"
path = "https://git.sr.ht/~blueingreen/base16-btop"
themes-dir = "colors"
#hook = "ln -sf %f ~/.config/btop/themes/base16.theme"
#hook = "mkdir -p ~/.config/btop/themes && ln -sf %f ~/.config/btop/themes/base16.theme"
hook = "mkdir -p ~/.config/btop/themes && ln -sf $TINTY_THEME_FILE_PATH ~/.config/btop/themes/base16.theme"
supported-systems = ["base16"]
