# shellcheck shell=bash
# Bash aliases sourced by ~/.config/bash/bashrc

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# grep colors
alias grep='grep --color=auto'
