# Bash aliases sourced by ~/.config/bash/bashrc

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# vim is actually vi, but use custom vimrc
alias vim="vi -u ~/.config/vim/vimrc"
