# https://alacritty.org/config-alacritty.html

[general]
import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 14

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 0

[window]
decorations = "None"
decorations_theme_variant = "None"
startup_mode = "Maximized"
